### ISSUE TITLE
results: choosing the features

### ISSUE THREAD

**Issue by MSusik** [inveniosoftware/beard#42] opened 2015-05-06 12:56 UTC
Using the old claimed set (~700000 claimed signatures) and 640000 pairs for training (available in `/home/scarli/allPairs.json`) I run the algorithm for learning the distance model. The algorithm eliminated least important features one after another. After each elimination the algorithm was rerun. Here are the results for `roc_auc_curve` where the training set had 91428 pairs, and the rest was used for cross validation.

The training set was chosen in this way:
``` python
pairs = cPickle.load(open('allPairs.json', 'r'))
random.seed(17340)
random.shuffle(pairs)
l = len(X)/7
training_sets = (X[:l], y[:l])
```

Here are the results. Every row shows an algorthm run for all the features from given row and all the rows above.

| Features                     | Result                         |
|-----------------------------|-----------------------------|
| coauthors_similarity  |                                      |
| author_full_name_similarity |                                      |
| title_similarity             |  0.96354                                    |
| author_other_names_similarity  | 0.97853  |
| affiliation_similarity   | 0.98270 |
| year_diff | 0.98339 |
| keywords_similarity  | 0.98384 |
| abstract_similarity     | 0.98422 |
| journal_similarity       | 0.98492 |
| author_initials_similarity | 0.98590 |
| collaborations_similarity | 0.98688 |
| references_similarity | 0.98723 |

Please not that `subjects_similarity` was not included. Also, `year_diff` might be improved to better handle cases with only one date available.

**Comment by glouppe** [comment] 2015-08-06 11:27
Duplicate of #54. We will decide what subset to include in the "fast" version depending on the results of the batch of experiments currently going for the paper.

**Closed by glouppe** 2015-08-06 11:27 UTC
Labels: Results
